name: Build

on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
    name: Build
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: sh .github/build.sh
